# Generated by Django 5.1.6 on 2025-03-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_token_alter_user_role_alter_user_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
